n=-10:10;
x=(-0.9).^n;
k=-200:200;
w=(pi/100)*k;
x=x*(exp(-j*(pi/100)*(n'*k)));
magx=abs(x);
angx=angle(x);
subplot(2,1,1);
plot(w/pi,magx);
grid;
xlabel('frequency in pi');
ylabel('mod');
title('magnitude part');
subplot(2,1,2);
plot(w/pi,angx/pi);
grid;
xlabel('frequency in pi');
ylabel('frequency in pi');
title('phase part');